//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChungsCatering
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ChungsDatabaseEntities1 : DbContext
    {
        public ChungsDatabaseEntities1()
            : base("name=ChungsDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ReservationDate> ReservationDates { get; set; }
        public virtual DbSet<ReservationDescription> ReservationDescriptions { get; set; }
        public virtual DbSet<ReservationStatu> ReservationStatus { get; set; }
        public virtual DbSet<ReservationUser> ReservationUsers { get; set; }
        public virtual DbSet<SeatStatu> SeatStatus { get; set; }
        public IEnumerable<object> ReservationUser { get; internal set; }
    }
}
