//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChungsCatering
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string ReservationType { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<int> OrderID { get; set; }
    }
}
